### ISSUE TITLE
Issues on non-ix86 architectures

### ISSUE THREAD

**Issue by michel-slm** [DanielStutzbach/blist#1]
The three patches in my form of blist address the following issues; a pull request has been made.

fastcall-ix86-only: this one actually just fixes some warnings: the
fastcall convention for GCC really only makes sense on ix86 (IA-32),
as on all our other supported platforms (x86_64, ppc, ppc64) the
default convention is already to put the first few arguments in
registers

remove-unsafe-tests: disable some tests that use out-of-range
integers: on non-ix86, they cause segmentation faults

use-upstream-macros: for some reason, Py_RETURN_TRUE and
Py_RETURN_FALSE are redefined, after they are already used in the file
(but with the same definition as the original). This patch removes
them

**Comment by DanielStutzbach** [comment]
Fixed in blist 1.0.2.
