### ISSUE TITLE
Write documentation for all types and methods

### ISSUE THREAD

**Issue by DanielStutzbach** [DanielStutzbach/blist#21]

**Comment by fmark** [comment]
It would be great if the documentation for methods could include their asymptotic run-time.

**Comment by DanielStutzbach** [comment]
I've written documentation for blist, sortedset, sortedlist, weaksortedset, and weaksortedlist.  Still to-do: sorteddict and btuple.

http://stutzbachenterprises.com/blist-doc/

**Comment by fmark** [comment]
This is fantastic, thank you!  Especially for someone relatively new to python and thus not familiar with the idomatic expectations of how a class would behave (for example, the use of "del" to remove elements).

**Comment by DanielStutzbach** [comment]
I'm glad it helps!  Let me know if you spot any typos or have any questions. :-)

**Comment by fmark** [comment]
Just returning to my blist using code, and wanted to let you know how happy I am about having good docs :)  Especially with the asymptotic behaviour.
