### ISSUE TITLE
sorteddict and btuple have meaningless __slots__, other collections have no __slots__ at all

### ISSUE THREAD

**Issue by zuo** [DanielStutzbach/blist#29]
When subclassing `sorteddict` I defined `__slots__` attribute and realized that it was futile, because -- although sorteddict **have** `__slots__`, it's meaningless, because some superclasses (from `_abcoll`...) have not. Some other collections don't have `__slots__` at all... It'd be nice to be able make use of `__slots__`... (sometimes there are plenty of collection instances and that's my case).

```
Python 3.1.2 (release31-maint, Sep 26 2010, 13:51:01) 
[GCC 4.4.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from blist import *
>>> bl = blist()
>>> bl.spam = 3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_blist.blist' object has no attribute 'spam'
>>> 
>>> bt = btuple()
>>> bt.spam = 3
>>> btuple.__slots__
['_hash', '_blist']
>>> 
>>> sd = sorteddict()
>>> sd.spam = 3
>>> sorteddict.__slots__
['_sortedkeys', '_map']
>>> 
>>> sl = sortedlist()
>>> sl.spam = 3
>>> sl.__slots__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'sortedlist' object has no attribute '__slots__'
>>> 
>>> s = sortedset()
>>> s.spam = 3
>>> sortedset.__slots__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'sortedset' has no attribute '__slots__'
>>> 
>>> wsl = weaksortedlist()
>>> wsl.spam = 3
>>> wsl.__slots__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'weaksortedlist' object has no attribute '__slots__'
>>> 
>>> ws = weaksortedset()
>>> ws.spam = 3
>>> ws.__slots__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'weaksortedset' object has no attribute '__slots__'
```

**Comment by DanielStutzbach** [comment]
What do you propose as a solution?

**Comment by zuo** [comment]
The issue inspired me to draft a small `clonetools` package. In this case `flatmirror()` from http://github.com/zuo/Zuo-s-Recipes-and-Drafts/blob/master/clonetools/flatmirror.py could be useful -- it's suitable for ABCs from `collections`; they do not use `super()` nor class names in methods (`flatmirror()` is also slighter, simpler and better tested than `clonecls()`).

The other possibility I see is to remove meaningless `__slots__` from `btuple` and `sorteddict` to keep consistency.

**Comment by DanielStutzbach** [comment]
I removed the meaningless `__slots__` declarations in blist 1.3.
