### ISSUE TITLE
No longer installs correctly in Python 3

### ISSUE THREAD

**Issue by dsemi** [DanielStutzbach/blist#53]
I've tried install through pip and just downloading and running the install script.  I always get the same error: error: invalid command 'bdist_egg', and that error leads to some import errors and others, but that's the first error I run into.

Could this have something to do with setuptools and distribute merging?

Full output when warnings/errors begin: 

<pre>
/usr/lib/python3.3/distutils/dist.py:257: UserWarning: Unknown distribution option: 'entry_points'

  warnings.warn(msg)

/usr/lib/python3.3/distutils/dist.py:257: UserWarning: Unknown distribution option: 'zip_safe'

  warnings.warn(msg)

/usr/lib/python3.3/distutils/dist.py:257: UserWarning: Unknown distribution option: 'test_suite'

  warnings.warn(msg)

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]

   or: setup.py --help [cmd1 cmd2 ...]

   or: setup.py --help-commands

   or: setup.py cmd --help

error: invalid command 'bdist_egg'

/tmp/pip_build_root/blist/distribute-0.6.12-py3.3.egg

Traceback (most recent call last):

  File "./distribute_setup.py", line 143, in use_setuptools

    raise ImportError

ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip_build_root/blist/setup.py", line 5, in <module>

    distribute_setup.use_setuptools()

  File "./distribute_setup.py", line 145, in use_setuptools

    return _do_download(version, download_base, to_dir, download_delay)

  File "./distribute_setup.py", line 125, in _do_download

    _build_egg(egg, tarball, to_dir)

  File "./distribute_setup.py", line 116, in _build_egg

    raise IOError('Could not build the egg.')

OSError: Could not build the egg.
</pre>

**Comment by DanielStutzbach** [comment]
Yes, it has something to do with distribute and setuptools merging.  I spent a little time tinkering with it, but the solution was not as obvious as I had hoped.  I'm swamped this week, but should have some time to dig into it next week.  Alternately, if you can figure it out, a patch would be most welcome. :-)

**Comment by dsemi** [comment]
At first glance, I can see that on line 140 of distribute_setup.py has:

<pre>if not hasattr(pkg_resources, '_distribute'):</pre>

and _distribute is no longer a property of setuptools.  The first error from above occurred in that try-catch block, so I'd say that's a good place to start.  I should have time later tonight to take a closer look.

**Comment by dsemi** [comment]
Confirmed working for me at least
https://github.com/DanielStutzbach/blist/pull/54

**Comment by DanielStutzbach** [comment]
I accepted your pull request.  I'll leave this issue open to remind me to do some more testing and upload a new build to pypi.

**Comment by DanielStutzbach** [comment]
Also: thanks! :-)

**Comment by tallforasmurf** [comment]
More recent note for anyone who runs into the problem with the latest blist and Python 3.3: if you first, "easy_install -U setuptools" to get them up to date (note "pip -U setuptools" will fail with an error message), you can then do "pip -U blist" and it will work.

**Comment by eode** [comment]
Thank you for that comment, @tallforasmurf.

**Comment by eode** [comment]
..should that be considered a continuation of this bug, or a new one?

**Comment by DanielStutzbach** [comment]
Should be fixed with blist 1.3.5, which I just uploaded to PyPi.  Let me know if you have any further trouble!
