### ISSUE TITLE
pip install blist fails

### ISSUE THREAD

**Issue by babartareen** [DanielStutzbach/blist#65]
I am getting following error when installing blist through pip on Mac OSX (10.9.2). 

> building 'blist._blist' extension
> 
> creating build/temp.macosx-10.9-intel-2.7
> 
> creating build/temp.macosx-10.9-intel-2.7/blist
> 
> cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386
> -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -DBLIST_FLOAT_RADIX_SORT=1 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
> -c blist/_blist.c -o build/temp.macosx-10.9-intel-2.7/blist/_blist.o
> 
> clang: error: unknown argument: '-mno-fused-madd'
> [-Wunused-command-line-argument-hard-error-in-future]
> 
> clang: note: this will be a hard error (cannot be downgraded to a
> warning) in the future
> 
> error: command 'cc' failed with exit status 1
> 
> ---------------------------------------- Cleaning up... Command /usr/bin/python -c "import setuptools,
> tokenize;**file**='/private/tmp/pip_build_root/blist/setup.py';exec(compile(getattr(tokenize,
> 'open', open)(**file**).read().replace('\r\n', '\n'), **file**,
> 'exec'))" install --record /tmp/pip-ZTLZf_-record/install-record.txt
> --single-version-externally-managed --compile failed with error code 1 in /private/tmp/pip_build_root/blist Storing debug log for failure in
> /Users/babar.tareen/Library/Logs/pip.log

clang --version

> Apple LLVM version 5.1 (clang-503.0.38) (based on LLVM 3.4svn)
> Target: x86_64-apple-darwin13.1.0
> Thread model: posix

**Comment by DanielStutzbach** [comment]
This is a problem is due to an incompatibility introduced with the latest version of Apple's Xcode.  The problem is not with blist; you will get the same error when trying to install any binary extension module.

There's a discussion and some possible solutions here:
http://stackoverflow.com/questions/22313407/clang-error-unknown-argument-mno-fused-madd-python-package-installation-fa

Hope that helps!

**Comment by babartareen** [comment]
The SO answer helped. With those flags set, blist installed just fine. Thanks.
