### ISSUE TITLE
Unable to install blist in windows 7 x64 bit operating system

### ISSUE THREAD

**Issue by rajeshhcu** [DanielStutzbach/blist#67]
Hi,

I am  trying to install blist on windows 7 x64 bit OS. 

I am using MinGW32 for compilation, but  it is raising the "bad reloc error".

Could you please send us the complete prerequisites and steps for installing blist?

I am using python 2.7.1 as part of my project. Also please suggest if any older versions of blist are available

**Comment by DanielStutzbach** [comment]
The blist package requires a Python installation and a working compiler tool chain that can build C extension modules for the installed version of Python.  It sounds like your tool chain is not set up properly to build C extension modules for the Python you have installed.  Unfortunately, I cannot help diagnose platform-specific issues of getting your environment set up correctly.  I suggest searching the web to see if other people have encountered similar errors while building C extension modules with MinGW32.
