### ISSUE TITLE
pypi links dead?

### ISSUE THREAD

**Issue by tallforasmurf** [DanielStutzbach/blist#71]
The pypi page (https://pypi.python.org/pypi/blist/1.3.6) refers for the home page and doc to stutzbachenterprises.com, but this server appears to be dead; it does not respond to http, and mail to daniel@stutzbachenterprises.com is rejected "452 4.3.1 Insufficient system storage".

**Comment by DanielStutzbach** [comment]
Oops.  Fixed!
