### ISSUE TITLE
keysview, valuesview accept some negative indices

### ISSUE THREAD

**Issue by tallforasmurf** [DanielStutzbach/blist#74]
Writing a unit-test case for code that depends on a sorteddict, I test the case of passing invalid index values to a method that depends on a keysvalue[index] and a valuesview[index].

```
    def getstuff(self, j):
        try:
            return self.values_view[j]
        except:
            # report error
```

To my surprise I found that passing j<0 did not raise an exception, provided abs(j)<=len(self.values_view), in fact it returns `self.values_view[len(self.values_view)+j]` and only raises IndexError when the index is outside this mirror-range.

Is this expected behavior?

**Comment by DanielStutzbach** [comment]
Yes.  This is how all sequences in Python work, such as list() and tuple().
