### ISSUE TITLE
Assuming this project is no longer maintained?

### ISSUE THREAD

**Issue by mzpqnxow** [DanielStutzbach/blist#96]
Hello, thanks for this excellent project, I use quite a bit with some of the large datasets I work with where numpy arrays aren't the best solution for whatever reason

Am I correct that this project is no longer maintained? I see it's been a long time since any commits were made and that issues are not answered (so not sure this will be any exception!)

**Comment by DanielStutzbach** [comment]
I'm still here. :-)

--
Daniel Stutzbach
(writing from my phone)

**Comment by mzpqnxow** [comment]
Ah! Great, thanks! Well this issue can be closed then :)
